CREATE TABLE IF NOT EXISTS users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	content TEXT NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	author SERIAL REFERENCES users(id)
);

ALTER TABLE
	posts DROP COLUMN IF EXISTS created_at;

ALTER TABLE
	posts
ADD
	COLUMN IF NOT EXISTS creation_date TIMESTAMP NOT NULL DEFAULT NOW();

CREATE TABLE IF NOT EXISTS session_tokens (
	id SERIAL PRIMARY KEY,
	token VARCHAR UNIQUE NOT NULL,
	user_id SERIAL REFERENCES users(id),
	created_at TIMESTAMP NOT NULL DEFAULT NOW()
);